// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oq6cVC1upxxiCown6jNaJmRD56Y0zDo',
    appId: '1:624561100662:web:d6077b2b0e7d5171e5cc57',
    messagingSenderId: '624561100662',
    projectId: 'parkingapp-c53d1',
    authDomain: 'parkingapp-c53d1.firebaseapp.com',
    storageBucket: 'parkingapp-c53d1.firebasestorage.app',
    measurementId: 'G-Z0DSFGFD4Z',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oq6cVC1upxxiCown6jNaJmRD56Y0zDo',
    appId: '1:624561100662:web:0e1fa1998a67f962e5cc57',
    messagingSenderId: '624561100662',
    projectId: 'parkingapp-c53d1',
    authDomain: 'parkingapp-c53d1.firebaseapp.com',
    storageBucket: 'parkingapp-c53d1.firebasestorage.app',
    measurementId: 'G-W50TZCHECD',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYsuWmsXXYhrQ14L8ljXXKaRXCa-DKpxA',
    appId: '1:624561100662:android:335abcfc18d5701fe5cc57',
    messagingSenderId: '624561100662',
    projectId: 'parkingapp-c53d1',
    storageBucket: 'parkingapp-c53d1.firebasestorage.app',
  );
}
