// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBot9VRlJh5M5MrYCvLbJy5exe1skxNT8',
    appId: '1:251585031194:web:50282aaa6fa44b37af35a3',
    messagingSenderId: '251585031194',
    projectId: 'parking-app-2e0bb',
    authDomain: 'parking-app-2e0bb.firebaseapp.com',
    storageBucket: 'parking-app-2e0bb.firebasestorage.app',
    measurementId: 'G-8CFV060FFY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBot9VRlJh5M5MrYCvLbJy5exe1skxNT8',
    appId: '1:251585031194:web:5ad92bc448abccc2af35a3',
    messagingSenderId: '251585031194',
    projectId: 'parking-app-2e0bb',
    authDomain: 'parking-app-2e0bb.firebaseapp.com',
    storageBucket: 'parking-app-2e0bb.firebasestorage.app',
    measurementId: 'G-QXWNMYVE1H',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPWkiddpk7i5EOE7U9ZTED-hcwaqsGAzE',
    appId: '1:251585031194:android:18cf88ca9a130224af35a3',
    messagingSenderId: '251585031194',
    projectId: 'parking-app-2e0bb',
    storageBucket: 'parking-app-2e0bb.firebasestorage.app',
  );
}
